# Generated by Django 3.1.3 on 2020-11-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120)),
                ('building_num', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=120)),
                ('zipcode', models.CharField(max_length=10)),
                ('is_warehouse', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.IntegerField()),
                ('time', models.IntegerField()),
                ('trucks', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
